###################
### MY PROGRAMS ###
###################
$browser = firefox
$terminal = wezterm
$fileManager = dolphin
#$menu = tofi-drun -c ~/.config/tofi/configA --drun-launch=true
$menu = rofi -show drun
$colorPicker = hyprpicker

#################
### AUTOSTART ###
#################
exec-once = [workspace 1 silent] firefox
exec-once = [workspace 2 silent] vesktop
exec-once = [workspace 3 silent] spotify
exec-once = [workspace 4 silent] wezterm

exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once = ags
exec-once = hyprpanel


