#############
### INPUT ###
#############

cursor {
	no_hardware_cursors = true
}
input {
    kb_layout = se
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}


gestures {
    workspace_swipe = false
}

device {
    name = logitech-usb-receiver
    sensitivity = -0.8
}
