##############################
### WINDOWS AND WORKSPACES ###
##############################

#windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# Custom window rules
windowrulev2 = opacity 0.90 0.90, class:^(Spotify)$
windowrulev2 = opacity 0.90 0.90, class:^(vesktop)$
windowrulev2 = opacity 0.90 0.90, class:^(org.wezfurlong.wezterm)$
#windowrulev2 = opacity 0.90 0.90, class:^(org.prismlauncher.PrismLauncher)$
#windowrulev2 = opacity 0.90 0.90, title:^(Library)$
windowrulev2 = float, title:^(Library)$
windowrulev2 = center, title:^(Library)$
windowrulev2 = size 800 500, title:^(Library)$
windowrulev2 = workspace 2, class:^(vesktop)$
windowrulev2 = workspace 3, class:^(Spotify)$

